# Generated by Django 3.2.8 on 2021-12-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_alter_subscription_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=191)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.subscriptionorder', unique=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
