# Generated by Django 3.2.8 on 2021-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20211208_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=191)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
