# Generated by Django 3.2.8 on 2021-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_offer_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
