# Generated by Django 3.2.9 on 2021-11-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20211116_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_coords_lat',
            field=models.FloatField(default=54.7007582),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_coords_lng',
            field=models.FloatField(default=24.9728598),
        ),
    ]
