# Generated by Django 3.2.9 on 2021-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20211125_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lng',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
