# Generated by Django 3.2.8 on 2021-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20211211_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_quantity',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
