# Generated by Django 3.2.9 on 2021-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20211125_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lng',
            field=models.FloatField(default=0),
        ),
    ]
