# Generated by Django 3.2.9 on 2021-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20211130_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lng',
            field=models.FloatField(),
        ),
    ]
