# Generated by Django 3.2.9 on 2021-11-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20211130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_coords_lng',
            field=models.FloatField(default=0),
        ),
    ]
