# Generated by Django 3.2.9 on 2021-11-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20211130_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_coords_lat',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_coords_lng',
        ),
    ]
