# Generated by Django 3.2.8 on 2021-12-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
