# Generated by Django 3.2.9 on 2021-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20211201_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_coords_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_coords_lng',
            field=models.FloatField(default=0),
        ),
    ]
