# Generated by Django 3.2.8 on 2021-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211030_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iscustomer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isseller',
            field=models.BooleanField(default=False),
        ),
    ]
