# Generated by Django 3.2.8 on 2021-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='issubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
